### ISSUE TITLE
failed to download KEGG xml/png files

### ISSUE THREAD

**Issue by javadnoorb** [datapplab/pathview#13]
Hi. When I run something similar to the following:
```pathview(gene.data=kegg_gene_list, pathway.id="hsa04110", species = 'hsa', same.layer=FALSE)```
I get this error:

```
Info: Downloading xml files for hsa04110, 1/1 pathways..
Warning: Download of hsa04110 xml file failed!
This pathway may not exist!
Info: Downloading png files for hsa04110, 1/1 pathways..
Warning: Download of hsa04110 png file failed!
This pathway may not exist!
Warning: Failed to download KEGG xml/png files, hsa04110 skipped!
```

This used to work about two weeks ago or so. I wonder if the error is related to changes on the KEGG API and similar to this:
https://github.com/YuLab-SMU/clusterProfiler/issues/470

-Thanks

**Comment by mewinners** [comment]
hello! 
a similar error happened to me, as the following picture:
![Code_y6CBL0FTik](https://user-images.githubusercontent.com/74438905/173535849-f0824ee0-2d7c-4f94-8086-a609400e95f5.png)

do you have any advices for me to solve this problem?

**Comment by javadnoorb** [comment]
Hi. I've made a fix here #14. It worked for me. Just use those instructions for now. Hopefully the main repo will be fixed soon.

**Comment by mewinners** [comment]
> Hi. I've made a fix here #14. It worked for me. Just use those instructions for now. Hopefully the main repo will be fixed soon.

I have tried already, but it is 'https' already which you can see it from screenshot.
And I also tried install dev, didn't work either.

**Comment by MoritzKaufmann** [comment]
Hi both, 

I had the same issue as mewinners. However the newly installation from the branch as suggested by javadnoorb worked for me.
Thank you very much.

Best
Moritz

**Comment by guidohooiveld** [comment]
> > Hi. I've made a fix here #14. It worked for me. Just use those instructions for now. Hopefully the main repo will be fixed soon.
> 
> I have tried already, but it is 'https' already which you can see it from screenshot. And I also tried install dev, didn't work either.

It also worked for me, although installation of the PR did not work first time. After modifying the 'URL' of Javad's repo, it nicely installed and `pathview` worked again as expected. So please double-check that you indeed installed the PR! 

See: https://github.com/datapplab/pathview/pull/14#issuecomment-1161736751

**Comment by whiteorchid** [comment]
Dear guys, 

I tried the hsa04110, it works, while another one(map04150) does not work...  It seems works with name start with hsa, while not work for name start with map...

Thanks a lot for the guidance!

```
Info: Downloading xml files for hsamap04150, 1/1 pathways..
Warning: Download of hsamap04150 xml file failed!
This pathway may not exist!
Info: Downloading png files for hsamap04150, 1/1 pathways..
Warning: Download of hsamap04150 png file failed!
This pathway may not exist!
Warning: Failed to download KEGG xml/png files, hsamap04150 skipped!
Warning message:
In download.file(xml.url, xml.target, quiet = T) :
  cannot open URL 'https://rest.kegg.jp/get/hsamap04150/kgml': HTTP status was '404 Not Found'
```

**Comment by guidohooiveld** [comment]
Mmm, I just checked and I am able to download 'your' pathway hsa04150....??

```
> library(pathview)
> data(gse16873.d)
> data(demo.paths)
>  
> i <- 1
> pv.out <- pathview(gene.data = gse16873.d[, 1], pathway.id =
+                     c("04150"), species = "hsa",
+                     out.suffix = "gse16873", kegg.native = TRUE)
'select()' returned 1:1 mapping between keys and columns
Info: Working in directory E:/test
Info: Writing image file hsa04150.gse16873.png
> 
> packageVersion("pathview")  
[1] ‘1.36.0’
>
```

Downloaded file with expression data overlaid (hsa04150.gse16873.png):

![hsa04150 gse16873](https://user-images.githubusercontent.com/22979991/178247783-d532cac0-b827-4a22-87be-22fa682c77c1.png)

**Comment by guidohooiveld** [comment]
Just to add that there seems to be something strange (= not reproducible) going on with downloading data from the KEGG website through `pathview`.

- Apparently this problem may be depending on the platform you are using; likely how downloads are implemented. see e.g. https://support.bioconductor.org/p/9144999/#9145000
- I noticed that the patch/PR from Javad is based on `pathview` version 1.31.3. In other words, when installing the Javad's PR this will effectively install version 1.31.3.
- The current release version of `pathview` on Bioconductor is version 1.36.0. This means that by default the Javad's PR is overwritten when updating another Bioconductor package.
- The build report of `pathview` 1.36.0 shows an error when being build on a Windows machine (see: http://bioconductor.org/checkResults/release/bioc-LATEST/pathview/palomino3-buildsrc.html). The error is the **same** as yours! This is in line with the observation that the problem is related to the OS you are using.
- Yet, on my (Windows 10) machine `pathview` v1.36.0 works...?? However, since I also downloaded the pathway data for hsa04150 from KEGG with v1.31.1 installed (thus before updating to 1.36.0) it could be that it worked with the release version of `pathview` (1.36.) because R or KEGG-server somehow 'remembers' the 'old' setting for this already downloaded pathway?? Cookie??
- In case you still have problems, my suggestion would be to start a fresh R-session, then reinstall Javad's PR by: `devtools::install_github("javadnoorb/pathview")`, and next perform you analysis based on this older version of `pathview`. I don't think that using an older version will be a big issue since the further development of `pathview` seems currently to be limited.
