### ISSUE TITLE
Download the pathway start with name "mapxxxxx"

### ISSUE THREAD

**Issue by whiteorchid** [datapplab/pathview#17]
Dear guys,

Is there a way to work for the pathways started with the name "mapXXXXX", for example, **map04750**. https://www.kegg.jp/entry/map04750 ? 

Though tried manually(to avoid the paste of hsa to map04750), try(download.file("https://rest.kegg.jp/get/hsamap04750/kgml","./map04750.xml", quiet = F))
The download XML file has an error. 

Thank you very much for your guidance!

```

Info: Downloading xml files for hsamap04750, 1/1 pathways..
Warning: Download of hsamap04750 xml file failed!
This pathway may not exist!
Info: Downloading png files for hsamap04750, 1/1 pathways..
Warning: Download of hsamap04750 png file failed!
This pathway may not exist!
Warning: Failed to download KEGG xml/png files, hsamap04750 skipped!
Warning message:
In download.file(xml.url, xml.target, quiet = T) :
  cannot open URL 'https://rest.kegg.jp/get/hsamap04750/kgml': HTTP status was '404 Not Found'
```

**Comment by guidohooiveld** [comment]
According to KEGG, pathways beginning with 'map' are the manually drawn reference pathways. See: https://www.genome.jp/kegg/document/help_pathway.html

I do not how to easily 'tweak' `pathview` to download the PNG of these 'map' pathways, but by using the [Bioconductor package](https://bioconductor.org/packages/release/bioc/html/KEGGREST.html) `KEGGREST` it is very straightforward:

```
> library(KEGGREST)
> library(png)
> 
> # map ids of 3 random pathways:
> kegg_pw_ids <- c("map04110", "map00010", "map01100")
> 
> # to save pathway maps as PNG images
> sapply(kegg_pw_ids, function (x) writePNG(keggGet(x,"image"), target=paste(x,".png",sep="")))
$map04110
NULL

$map00010
NULL

$map01100
NULL

>
``` 

AFAIK you cannot use the map ids as such to download KEGG's KGML files, because these KGML files (should?) contain species-specific information. Most 'species-agnostic' could be the KO ids ([KEGG orthology ids](https://www.genome.jp/kegg/ko.html)).

To download these you could simply use the function `download.kegg` from` pathview`.

```
> library(pathview)
> kegg_pw_ids <- c("map04110", "map00010", "map01100")
> 
> # substitute 'map', and download KO-based KGML (and png!) files
> download.kegg(pathway.id = sub("map", "", kegg_pw_ids), species = "ko")
Info: Downloading xml files for ko04110, 1/3 pathways..
Info: Downloading xml files for ko00010, 2/3 pathways..
Info: Downloading xml files for ko01100, 3/3 pathways..
Info: Downloading png files for ko04110, 1/3 pathways..
Info: Downloading png files for ko00010, 2/3 pathways..
Info: Downloading png files for ko01100, 3/3 pathways..
  ko04110   ko00010   ko01100 
"succeed" "succeed" "succeed" 
> 
> # idem, but for human
> download.kegg(pathway.id = sub("map", "", kegg_pw_ids), species = "hsa")
Info: Downloading xml files for hsa04110, 1/3 pathways..
Info: Downloading xml files for hsa00010, 2/3 pathways..
Info: Downloading xml files for hsa01100, 3/3 pathways..
Info: Downloading png files for hsa04110, 1/3 pathways..
Info: Downloading png files for hsa00010, 2/3 pathways..
Info: Downloading png files for hsa01100, 3/3 pathways..
 hsa04110  hsa00010  hsa01100 
"succeed" "succeed" "succeed" 
> 
> 
> packageVersion("pathview")  
[1] ‘1.31.3’
>
```

Note that I used the modified version of `pathview` (Javad's PR with fix for https); as discussed here: https://github.com/datapplab/pathview/issues/13

**Comment by whiteorchid** [comment]
Thanks a lot! The mapxxx is indeed the same as hsaxxx(previous I saw mapxxx is differing from hsaxxx, which probably mistakenly compared). 

Thank you very much for your guidance! Appreciate!
