### ISSUE TITLE
Different scores for the same gene in non-native plots

### ISSUE THREAD

**Issue by leonorrib** [datapplab/pathview#4]
Dear "pathview" team,

I have plotted time series data in a non-native KEGG plot and I have the impression there is a bug. The same gene appears multiple times in the plot but it doesn't show similiar colors in all of them. See attached example with the Yap1 gene. The example is from the Hippo signaling pathway in mice (ie. mmu04390). And I'm just showing a small portion of the actual figure, just the top left area.

I'm using version 1.28.1 of the pathview package.

Perhaps this is a bug or perhaps there is something I'm doing wrong and you can help me.

Best regards,
Leonor
<img width="553" alt="mmu04390 Hippo signaling pathway" src="https://user-images.githubusercontent.com/33957151/119700931-1abc2400-be54-11eb-984a-89396e1bde0b.png">

**Comment by wluo1** [comment]
Dear Leonor,
Thanks for the interest and the question. I agree this is a little confusing. It is due to the fact that some gene nodes cover multiple related genes. The two Yap1 gene nodes are actually different here. Yap1 node with Smad1 and Smad4 include Yap1 gene only, but the other Yap1 node include both Yap1 and Wwtr1 (TAZ). When there are multiple genes, we only use the most representative one as label as to avoid the extremely long labels with dozens of genes.
This is more clear in the native KEGG graph, where these two nodes are label as YAP and YAP/TAZ. https://www.genome.jp/pathway/mmu04390
Unfornately, KEGG XML files do not provide such label data, and we are only able to use the gene symbols as labels in the graphviz (non-native ) version.
HTHs.
