### ISSUE TITLE
licensing/copyright question

### ISSUE THREAD

**Issue by ivokwee** [datapplab/pathview#8]
1.  At startup pathview says that it downloads KEGG data and non-academic users may need a license. Seems pathview downloads XML and PNG files from the KEGG servers. Exactly, what is supposed to be under license, the downloading (as paid service) or the use of these XML/PNG files (copyright)? 

2. After pathview modifies the PNG file with the expression coloring, is the resulting image still under copyright of KEGG or can we use that image freely? For the original image, it seems we need to ask explicit permission for publications, see https://www.kegg.jp/feedback/copyright.html

**Comment by chiwwong** [comment]
A follow-up on this: is it possible to allow the user not to put the stamp on the graph? Now I think there is a default of putting the stamp on the graph, it is especially problematic when using the graphviz view.

**Comment by joannawolthuis** [comment]
I'd like to ask point 1 as well, I would like to use the KEGG-style visualisations in my publication but am not sure if I should be asking for permission. Thanks for your work on this package!

**Comment by wluo1** [comment]
All data Pathview downloads from KEGG are open-access and publically available (instead of via subscription). The stamps acknowledge that the source pathway data come from KEGG. You don’t have to use the stamp, and please check the package documentation on this.
Pathview is an open-source tool under GPL. It has been widely used by the scientific community. It is the users’ decision and responsibility if they use Pathview or if they want to communicate with KEGG.
